server:
  port: 8000
spring:
  application:
    name: mall-member
  datasource:
    username: root
    password: root
    url:  jdbc:mysql://localhost:3306/mall_ums?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
