server:
  port: 10000
spring:
  application:
    name: mall-product
  datasource:
    username: root
    password: root
    url:  jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
