server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        bucket: guli-mall-luosheep
        endpoint: oss-cn-guangzhou.aliyuncs.com
      access-key: ***
      secret-key: ***
  application:
    name: mall-third-party

